### ISSUE TITLE
Idea: Lack of Interaction between players (plz jobs)

### ISSUE THREAD

**Issue by BlueHNT** [Vault-Overseers/nuclear-14#207]
# Description

There is a lack of roles people can take even in survival to interact with each other. Making just a little tiny bit like doctor, farmer, guard and such would make even the wave survival run a bit smoother due to people having jobs.

Also having a dedicated doctor would mean people aren't entirely out of the round when one dies. Since there would be a defib. Maybe blood even.

# Media

![TGMC_9000_burn_damage](https://github.com/Vault-Overseers/nuclear-14/assets/79374236/91c9037b-98c4-4057-af34-917be1de9343)

**Comment by Peptide90** [comment]
Not a bad idea. The mode isn't really meant for roleplay though although you can do anything as the survivor role. All the roles are already coded so just need enabled for full release.

The wave mode checks for anyone specifically with the survivor role being alive.

**Comment by BlueHNT** [comment]
Some admins also build their own little trader place. That might be a good thing to use really.
