### ISSUE TITLE
Update request: Update to the loot pool

### ISSUE THREAD

**Issue by BlueHNT** [Vault-Overseers/nuclear-14#215]
# Description

The loot pool needs updating on certain weapons and ammo types. The ones I am aware of are as follows...

##### Battery
- multiplas
- plasma_pistol
- plasma_rifle
- plasma_urban

##### LMGs
- autorifle
- lmg

##### Pistols
- 22lr
- chinesepistol
- therspy?

##### Revolvers
- hunt_revolver
- magnum

##### Rifles
- battlerifle
- carbine
- r91
- servicerifle

##### Shotguns
- riotshotgun

##### SMGs
- 45SMG
- advance12mm

##### Snipers
- varmint

##### Battery
- microfusion
- plasma

##### Boxes
- 50anti-material

##### Magazines
5.56
- maglmg

12.7
- topmag

22lr
- pistolmag
- smgmag

45
- smgmag

308
- mag
- mag2

### Backpacks and Belts

There is only the hiking backpack military backpack added to the map itself. There is no way to get any backpack, belt or webbing other than those 2 world spawns.

### Clothing

Similar to backpacks there are too few in the pool and listing out all the ones which aren't added would be too lengthy.

### Armors, Helmets and protective equipment

Once again, there are too many to list as there is only a very short circulation of armors, gloves, boots and helmets. Some of which aren't even in circulation.

## Afternote

The best way to sort out the clothing and backpacks is for them to be in the loadout sections.

As for armors, belts and similar. There should be a limited amount in the pool which will be scrap and rare interesting ones with some unique around map.

**Comment by PatoGrone** [comment]
wanna win your blue name on discord? most of this can be done easylly by just adding their IDs to the loot pools. i can help you accomplish it.

**Comment by BlueHNT** [comment]
I'll look into it. But I don't understand C# or the game code.
