### ISSUE TITLE
Issue: Sack UI not appearing when interacting

### ISSUE THREAD

**Issue by BlueHNT** [Vault-Overseers/nuclear-14#216]
# Description

Unable to open or interact with sack other than put stuff in it.

# Reproduction

1. Open "sack" UI (E)
2. Nothing

# Expected behavior

1. Open "sack" UI (E)
2. "sack" UI opens

# Additional context

Inventory interaction is a bit broken with it.

**Comment by Peptide90** [comment]
Is this still the case or did I fix it?

**Comment by BlueHNT** [comment]
> Is this still the case or did I fix it?

It's fixed, though idk the diff between chem sack and fert sack. Probably good for farmers anyway.
