### ISSUE TITLE
Issue: Crafting Problems

### ISSUE THREAD

**Issue by BlueHNT** [Vault-Overseers/nuclear-14#225]
# Description

Welp, time to go over all this.

- Only "Sulfur Ore" is grindable for 10u of liquid sulfur
- normal "Sulfur" in processed form is liquid-able by using beaker on it. But if the sulfur is in a stack, it removes all stacks for 10 sulfur instead of removing 1 unit from the stack.
- There is no way to get paper or plastic
- There is no way to insert paper into workbench
- individual cartridge recipes are obsolete
- mining fertilizer feels weird, but mainly it has very low gain of it, since each ore is 10u of liquid fertilizer unlike Sulfur or Lead which each yield 50u liquid form or 5 pieces solid form.
- magazine recipes should yield empty magazines and not require gunpowder/lead in their crafting. Being able to make full ones is kind of weird, at least in my opinion.

**Comment by BlueHNT** [comment]
Also

- Ores look like normal rocks, it feels weird.

**Comment by BlueHNT** [comment]
some parts are fixed

**Comment by Peptide90** [comment]
Magazines one is just a shortcut to make large amounts at once, same with the box of ammo.

We can add empty mags easy for the 100 steel too.

**Comment by BlueHNT** [comment]
> Magazines one is just a shortcut to make large amounts at once, same with the box of ammo.
> 
> We can add empty mags easy for the 100 steel too.

I mean it's fine and all, but I feel like you should make empty mags and boxes of ammo. Making ammo individually is just a bloody nightmare since you can only hold 1 at a time anyway.
