### ISSUE TITLE
We need a cryosleep / SSD solution

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#274]
# Description

Currently when players leave I've been instructing them to find a bed at base and just go there.

Really we need a way to return items and open job slots. For most factions this could be a special bed or a radio desk that you interact with and it removes you from the round. Potentially returning all your items to a box nearby or removing them.

For all roles could have them on the map edge markers that are currently late join spots. Have them double up as round leaving spots.

**Comment by Peptide90** [comment]
https://github.com/crystallpunk-14/crystall-punk-14/pull/296

**Comment by BlueHNT** [comment]
So I got a simple but effective solution.

You know those borders you join with in latejoin? Make it so when you click em you insta-cryo after some popup of "This will cryo you, are you sure?" and some more of em around the map. Best around all major factions.

**Comment by Peptide90** [comment]
Added the cryo function to the edge of map spawners, 15 second timer so people cant abuse it to hide. changed the drawdepth too so people cant hide behind them anymore.
