### ISSUE TITLE
Character loadouts do not have tokens independent of each job

### ISSUE THREAD

**Issue by FrostRusty** [Vault-Overseers/nuclear-14#277]
# Description
The loadouts you can select for your job in the character creator use tokens you can allot to give yourself items to start with. Some stuff is pretty tame like cloth gloves but some stuff is pretty important like the NCR equipment kits. 

The issue is that points are not allotted per job. Instead it's more like you have a total amount of credits to spend on all the different jobs, meaning if you use 10 credits on NCR soldier to get a kit you'll only have 4 credits to go and customize any other job without first going and deselecting the kit on the NCR soldier.

# Reproduction
Enter the customize character screen during pre-round
Set a job to high priority and then save so that your character updates
Enter the loadout tab and select anything.
Set a different job to high priority and save again to update
Enter the loadout and you'll have the same amount of points despite having nothing equipped.

# Expected behavior
Points per loadout should be job dependent rather than account dependent. 

# Media

![image](https://github.com/Vault-Overseers/nuclear-14/assets/156849123/13195d73-a221-4364-a9e9-9cffb098a12d)
![image](https://github.com/Vault-Overseers/nuclear-14/assets/156849123/0f894ae4-bf5d-4eb7-af59-08c751d74165)
![image](https://github.com/Vault-Overseers/nuclear-14/assets/156849123/d8eb69da-553a-4a3c-b103-30f7ca71306a)
![image](https://github.com/Vault-Overseers/nuclear-14/assets/156849123/82c9c9df-0e6a-40e4-87e0-51212520597c)

# Additional context
There have been other loadout systems implemented on other servers like Frontier and Delta-V. I'm not sure how collaboration across forks works but I know that Frontier recently got a new license which matches the same license that Einstein Engines uses. If that's true then maybe they could help.

**Comment by VMSolidus** [comment]
The answer is never. Not going to happen. Frontier uses Wizden's version of loadouts, Einstein Engines has it's own version of loadouts. We will not, and cannot actually merge Wizden's loadouts. They have a different version of the game entirely.

**Comment by DangerRevolution** [comment]
> The answer is never. Not going to happen. Frontier uses Wizden's version of loadouts, Einstein Engines has it's own version of loadouts. We will not, and cannot actually merge Wizden's loadouts. They have a different version of the game entirely.

Did you read the rest of the issue?

**Comment by BlueHNT** [comment]
#372 this should more or less fix this `issue`
