### ISSUE TITLE
Terminal sprite directions

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#435]
Animation on one of the states is backwards.

![SS14 Loader_XCjhchKRrL](https://github.com/user-attachments/assets/4cb20fee-01d9-4e1c-80b1-6b617cee32a0)

**Comment by Peptide90** [comment]
Adding to this, the classic wall terminal has a pixel far away that needs deleted.

**Comment by justzick** [comment]
Fixed by #472.
