### ISSUE TITLE
Hey so how are we supposed to get table salt?

### ISSUE THREAD

**Issue by 6SpadesLuke** [Vault-Overseers/nuclear-14#482]
# Description

Table salt and brahmin milk is used to make butter.

I get that a special type of Brahmin butter is being made or is in concept but as of current we can't even make butter!

There's a lot of special meals I think I could come up with using butter and salt. (Or add just a bit more depth)

**Comment by MouseHatsForAll** [comment]
Maybe if we boil a bucket of purified water, it'd evaporate down to salt?
Otherwise, maybe make it so if you boil radiated and/or dirty water, you just get radium or mold respectively.
Just an idea.

**Comment by 6SpadesLuke** [comment]
I mean like, what if we gained the components of salt from creatures after grinding them down

like, what if we combined chemicals from creatures together in order to make salt?

and I think the boiling idea is cool

**Comment by 6SpadesLuke** [comment]
just did some research on water and wood, they both contain a miniscule amount of salt but this is fallout so it just works

**Comment by 6SpadesLuke** [comment]
so let's say heating up water above a campfire for ~30 seconds or so turns 10u of water into like 0.5u of table salt

**Comment by 6SpadesLuke** [comment]
and for wood lrts say that you smelt it down into charcoal and add liquid to it and you can separate the salt and the charcoal at a chemical bench or summ

**Comment by Peptide90** [comment]
I can add salt as a mined thing and maybe I can add seawater as a source too and heating will produce salt. Will work on this today.

**Comment by MutantMan2040** [comment]
Also just. pre war salt too, could come in shakers and in jars.

**Comment by MutantMan2040** [comment]
But yeah be cool too have multiple sources. I like being able too heat up sea water for it

**Comment by Peptide90** [comment]
Added salt shakers and stuff as well as salty water that can be boiled to get table salt.
