### ISSUE TITLE
Items are not visible on shelves anymore

### ISSUE THREAD

**Issue by MutantMan2040** [Vault-Overseers/nuclear-14#506]
After The Tall Wall update, items now appear under shelves, their sprites are invisible unless you right click the shelves too see whats under, if this could be fixed thatd be good, so mappers and shopkeepers can place zhit on shelves again.

**Comment by Peptide90** [comment]
There will be a PR or commit somewhere that changes shelves to a different drawdepth, just needs changed back. This will be the case with a few things but easy to do.

**Comment by MutantMan2040** [comment]
> There will be a PR or commit somewhere that changes shelves to a different drawdepth, just needs changed back. This will be the case with a few things but easy to do. 

Alright i will fix it with my next PR :)
