### ISSUE TITLE
Add jukebox with fallout songs

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#508]
title

prototypes/catalog/jukebox

**Comment by MrLopLop** [comment]
I'll try to do something, but I'm new to this, so don't rely on me :D

**Comment by MrLopLop** [comment]
I tried to migrate this system from another build, but nothing worked.
It's still too difficult for me.
UwU :(

**Comment by Peptide90** [comment]
I think it relies on my upstream merge which I'm part way through, so should be possible soon.
