### ISSUE TITLE
you cannot starve through normal means

### ISSUE THREAD

**Issue by 6SpadesLuke** [Vault-Overseers/nuclear-14#542]
# Description

You cannot starve through normal means unless you throw up a lotm

# Reproduction

1. Play game
2. Wait
3. Hunger doesn't go down

# Expected behavior

1. Play game
2. Wait
3. Hunger goes down
4. starve

# Additional context

mood pr might be affecting this

**Comment by 128th** [comment]
Yep. With amount of food and wild game out there each round ends with great abundance of food. You do get hungry but extremely slowly comparing to how quickly you get thirsty.

**Comment by 6SpadesLuke** [comment]
well that's really dumb, maybe it should be rebranded so they're either similar in speed or less food out there

**Comment by 6SpadesLuke** [comment]
auto correct is going to be the death of me
